### ISSUE TITLE
Specifying the requirements.txt

### ISSUE THREAD

**Issue by thraster** [Healthcare-Robotics/bodies-at-rest#12]
Hi henry, nice work you have done!
I was trying to setup your code recently, but find that the dependencies in requirements.txt didn't specifyied the appropriate version numbers, which caused some troubles during the setup...

I tried ChatGPT to list a new requirements file that may compatible with Python 2.7:

numpy==1.16.6
trimesh==3.21.6
pyrender==0.1.34
matplotlib==2.2.5
torch==0.4.1
torchvision==0.2.1
chumpy==0.70
opencv-python==4.5.1.48
scikit-learn==0.23.2
open3d-python==0.3.0
imutils==0.5.4
camera==0.2.1

but still cannot fix the problems, 
if possible, can you give us the requirements.txt with specifyied dependencies verison numbers?
Thanks a lot！

**Comment by henryclever** [comment]
Hi! I'm sorry you've run into these issues. I should have specified these versions when I published this repo, but I wasn't as proficient of a software engineer at the time and didn't think to do it.

From what I recall most of the libs were relatively straightforward except the versions of open3d and pyrender. And they also had some issues with deps I had to install via `apt-get`. which packages are you having trouble importing? 

Do you have a machine with 2.7 that I could ssh into? I don't have the ubuntu 16.04 / python 2.7 computer I built this on with me anymore. It's possible I could get it working with my ubuntu 18 computer, but I'd like to understand your issues better first before I dig into it that far.

-Henry

**Comment by henryclever** [comment]
From a look at the closed issues, I see that I got it working and specified some versions to help someone else with this -- look here -- https://github.com/Healthcare-Robotics/bodies-at-rest/issues/7 

A  couple differences (there are more):
```
python-opencv==3.4.8.29
opendr==0.76
```

**Comment by thraster** [comment]
Hi Henry! Thank you for your rapidly reply, I'm sorry that I haven't use SSH before, it may take some time to figure out how to use that.

The problem was occured when I ran the `pip install -r requirements.txt`, when it reachs the pyrender, errors occured:
![Screenshot from 2023-05-16 05-32-13](https://github.com/Healthcare-Robotics/bodies-at-rest/assets/101303906/5e5cc0ab-d948-4739-a2c5-8ecf11610b83)

I thought it could be fixed if I get the specified version number, that's why I'm trying to get it from you.

btw, I'm running this with ubuntu 18.04/ python 2.7

Thank you again, Henry!

-chester

**Comment by henryclever** [comment]
OK! Well, pyrender 0.1.45 is too new ... I would try something that was released in 2019 since that's when I developed much of this. It also looks like it's using trimesh 3.21.6.. definitely too new. I would try 3.4.xx or something.

Generally, try to build some list of deps that were all released sometime in 2019/ early 2020, and let me know what issues you run in to with that.

-Henry

**Comment by thraster** [comment]
Hi Henry, I think this might work now:

numpy==1.16.4
trimesh==2.35.39
pyrender==0.1.33
matplotlib==2.2.4
imageio==2.5.0
###################################################################
# I didn't install the Pytorch from the deps in this requirements.txt file.
# I installed them from the Pytorch.org using their command :
# !conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
torch==1.2.0
torchvision==0.4.0a0
###################################################################
chumpy==0.70
opencv-python==4.1.0.25
scikit-learn==0.20.3
open3d-python==0.7.0.0
imutils==0.5.3
camera==1.3.0

I already get acess in these code and have tried some dataset demostration, it's worked, but I haven't tried the training and other stuffs, so I will make commments if there are some problems with this specified deps

Thank you for your instrutions
