### ISSUE TITLE
Downloading real data?

### ISSUE THREAD

**Issue by wangzheallen** [Healthcare-Robotics/bodies-at-rest#2]
ERROR 403: Forbidden. when I run ./download_qt_real.sh.
And there is no download_real.sh

**Comment by henryclever** [comment]
Hi, 

Thanks for notifying me of these issues. I'm working on it now and I'll get back to you shortly.

**Comment by henryclever** [comment]
OK, the download_qt_real.sh should be fixed. I'll fix the other in a bit -

**Comment by wangzheallen** [comment]
Thanks! the download_qt_real.sh  works now!

**Comment by henryclever** [comment]
OK I've added a script for all the real data. If it works please close this issue, otherwise I will close it  this week.

Henry
