### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by leopqrz** [Healthcare-Robotics/bodies-at-rest#4]
Hi,

I'd like to know about the spatial and time synchronization of pressure mat + RGB video:

1 - What pressure mattress pixels correspond to what RGB image pixels in the camera?
2 - How were different sampling rates accounted for between the pressure mat and RGB camera?
3 - Were both devices connected to the same computer?

Thank you

**Comment by henryclever** [comment]
Hi, 

1. I'll have to look into this and get back to you. 
2. The data is not dynamic. It is static. So there isn't video data in the dataset. During data collection, participants did not move when data was captured. So even if the sample from one modality was say a quarter second behind another, the result is inconsequential. It was synchronized at a higher rate than that though, so there is virtually no issue from this.
3. Yes, I collected everything on the same computer.

-Henry

**Comment by henryclever** [comment]
Hi, regarding question #1. You can observe this with the `viz_real_cvpr_release.py` script in the PressurePose dataset visualization section in the readme file. The code in that script visualizes the calibrated images side by side as shown. There are four black dots at the corners of the bed on the RGB image, which are set in the python script. These correspond with the corner taxels on the pressure mat. The pressure mat is of course a lower resolution, so the mapping isn't 1-to-1, so there are a number of RGB pixels that coincide with each taxel on the mat.

-Henry
