### ISSUE TITLE
Measurement of Pressure Mattress

### ISSUE THREAD

**Issue by aajikar** [Healthcare-Robotics/bodies-at-rest#6]
HI Henry,

What are the physical dimension of the pressure mattress that was used with real patients? More specifically the dimension of the sensing area?

I was reading through your paper and I saw that the sensors form an array of 64x27; the top and bottom 9cm do not have sensors, and 6cm on the sides don't have sensors. 

Just wanted to know how big the mattress area is in inches or cm.

**Comment by henryclever** [comment]
Hi,

Sorry I was in the middle of moving and the last couple weeks have been very hectic. 

The sensing area is nominally 64 inches x 27 inches. However, it's not exactly that. In terms of meters:

- Pressure mat: 0.0286*64 x 0.0286*27/1.04 = 1.83 x 0.7425 meters
- Mattress: 0.0286*68 x 0.0286*33/1.04 = 1.945 x 0.9075 meters

This may be off very slightly (i.e. a few mm for the mat) but it's pretty darn close. And the fabric is somewhat stretchable so it's not exact from that either.

-Henry
